import JSZip from 'jszip';
import download from 'downloadjs';
import { Website } from '../interfaces';



export const downloadFiles = async (website: Website) => {
    const zip = new JSZip();
    zip.file("index.html", generateHtml(website));
    const content = await zip.generateAsync({type:"blob"})
    download(content, "website.zip", "application/zip");

}

function generateHtml(site: Website) {
    const html = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>${site.name}</title>
            <meta charset="utf-8"  />
        </head>

        <body>
            <p>Example of ${site.name} website that was generated by this app!</p>
        </body>
        </html>
    `;
    return html;
}
